"""Drive the *actual* ya||a simulator from Python.

ya||a (https://github.com/germannp/yalla) is a header-only C++/CUDA framework:
there is no library to link against — each model is a ``.cu`` file compiled
against ya||a's headers into a standalone GPU binary. This module makes that
usable as a stateful process-bigraph step:

1. **Resolve** a ya||a checkout (``YALLA_HOME`` env var → ``~/code/yalla`` →
   shallow ``git clone`` into a cache dir).
2. **Generate** a parametrized ``.cu`` from :data:`CU_TEMPLATE` whose ``main()``
   reads an initial population from a file, runs ``n_steps`` of
   ``bodies.take_step<force>(dt)``, and writes the final population back —
   so state round-trips across PBG ``update()`` calls.
3. **Compile** it once with ``nvcc`` (binary cached by a hash of the source +
   target arch) and **run** it per step, exchanging state via plain TSV files.

Everything that does not need a GPU — checkout resolution, source generation,
the state-file codec — is exercised by the offline test suite. The compile and
run steps require ``nvcc`` + an NVIDIA GPU; in their absence the bridge raises
:class:`YallaCudaUnavailable` with actionable guidance rather than silently
falling back to anything.

The force functions below mirror ya||a's own examples (``springs.cu``,
``sorting.cu``, ``passive_growth.cu``). ``spring`` is a verbatim port; the
type-dependent kernels follow the same ``__device__ float3 force(float3 Xi,
float3 r, float dist, int i, int j)`` contract and read a managed ``d_type``
array. Validate them against your ya||a version on a GPU host before relying on
the numbers.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
from pathlib import Path

import numpy as np

YALLA_REPO_URL = "https://github.com/germannp/yalla.git"
DEFAULT_CUDA_ARCH = "sm_60"

#: Force kernels the bridge can compile. Keys match
#: ``YallaReproductionProcess``'s ``force_kernel`` where the physics overlaps.
SUPPORTED_KERNELS = ("spring", "differential_adhesion", "relu")


class YallaCudaUnavailable(RuntimeError):
    """Raised when the real ya||a bridge needs a CUDA toolchain/GPU it can't find."""


# ---------------------------------------------------------------------------
# CUDA source generation
# ---------------------------------------------------------------------------

# Per-kernel device force function bodies. Each defines
#   __device__ float3 <name>(float3 Xi, float3 r, float dist, int i, int j)
# where r = Xi - Xj and dist = |r|. Returned float3 is summed into Xi's
# velocity by take_step, exactly as in ya||a's examples.
_FORCE_BODIES = {
    "spring": """
__device__ float3 pbg_force(float3 Xi, float3 r, float dist, int i, int j) {
    float3 dF{0.0f, 0.0f, 0.0f};
    if (i == j) return dF;
    // Hookean spring toward equilibrium length L_0 (verbatim springs.cu).
    dF = r * (P_L0 - dist) / dist;
    return dF;
}
""",
    "differential_adhesion": """
__device__ float3 pbg_force(float3 Xi, float3 r, float dist, int i, int j) {
    float3 dF{0.0f, 0.0f, 0.0f};
    if (i == j) return dF;
    if (dist > P_RMAX) return dF;            // finite interaction range
    // Type-dependent equilibrium spacing: like cells sit closer than unlike
    // cells, driving Steinberg differential-adhesion sorting (sorting.cu).
    float r_eq = (d_type[i] == d_type[j]) ? P_RMIN : (0.5f * (P_RMIN + P_RMAX));
    dF = r * (r_eq - dist) / dist;
    return dF;
}
""",
    "relu": """
__device__ float3 pbg_force(float3 Xi, float3 r, float dist, int i, int j) {
    float3 dF{0.0f, 0.0f, 0.0f};
    if (i == j) return dF;
    if (dist > P_RMAX) return dF;
    // ReLU-shaped adhesion: strong short-range repulsion, linear attraction
    // out to r_max (passive_growth.cu / migration.cu).
    float F = (dist < P_RMIN) ? (P_RMIN - dist) : 0.3f * (P_RMAX - dist);
    dF = r * F / dist;
    return dF;
}
""",
}

CU_TEMPLATE = r"""// Generated by pbg-yalla — do not edit by hand.
// Drives the real ya||a solver for a fixed population, reading the initial
// state from argv[1] and writing the final state to argv[2].
#include <cstdio>
#include <cstdlib>

#include "dtypes.cuh"
#include "inits.cuh"
#include "solvers.cuh"

// --- baked-in model parameters -------------------------------------------
const float P_L0   = {L_0}f;   // spring equilibrium length
const float P_RMIN = {r_min}f; // short-range / like-cell equilibrium
const float P_RMAX = {r_max}f; // interaction cutoff
const int   N_MAX  = {n_max};

// Cell-type labels, readable from device force functions (like sorting.cu).
__managed__ int d_type[{n_max}];

{force_body}

int main(int argc, char** argv) {{
    if (argc < 5) {{
        std::fprintf(stderr,
            "usage: %s <in.tsv> <out.tsv> <n_steps> <dt>\n", argv[0]);
        return 2;
    }}
    const char* in_path  = argv[1];
    const char* out_path = argv[2];
    const int   n_steps  = std::atoi(argv[3]);
    const float dt       = (float) std::atof(argv[4]);

    std::FILE* fin = std::fopen(in_path, "r");
    if (!fin) {{ std::perror("open in"); return 1; }}
    int n = 0;
    if (std::fscanf(fin, "%d", &n) != 1 || n <= 0 || n > N_MAX) {{
        std::fprintf(stderr, "bad cell count %d (max %d)\n", n, N_MAX);
        return 1;
    }}

    Solution<float3, Tile_solver> bodies{{n}};
    for (int i = 0; i < n; i++) {{
        float x, y, z; int t;
        if (std::fscanf(fin, "%f %f %f %d", &x, &y, &z, &t) != 4) {{
            std::fprintf(stderr, "short read at row %d\n", i);
            return 1;
        }}
        bodies.h_X[i].x = x;
        bodies.h_X[i].y = y;
        bodies.h_X[i].z = z;
        d_type[i] = t;
    }}
    std::fclose(fin);

    bodies.copy_to_device();
    for (int step = 0; step < n_steps; step++) {{
        bodies.take_step<pbg_force>(dt);
    }}
    bodies.copy_to_host();

    std::FILE* fout = std::fopen(out_path, "w");
    if (!fout) {{ std::perror("open out"); return 1; }}
    std::fprintf(fout, "%d\n", n);
    for (int i = 0; i < n; i++) {{
        std::fprintf(fout, "%.9g\t%.9g\t%.9g\t%d\n",
            bodies.h_X[i].x, bodies.h_X[i].y, bodies.h_X[i].z, d_type[i]);
    }}
    std::fclose(fout);
    return 0;
}}
"""


def generate_cu_source(*, force_kernel: str, L_0: float, r_min: float,
                       r_max: float, n_max: int) -> str:
    """Render the ``.cu`` source for one model configuration."""
    if force_kernel not in _FORCE_BODIES:
        raise ValueError(
            f"force_kernel {force_kernel!r} has no CUDA implementation; "
            f"bridge supports {SUPPORTED_KERNELS}. Use YallaReproductionProcess "
            f"for the other NumPy kernels.")
    return CU_TEMPLATE.format(
        L_0=float(L_0), r_min=float(r_min), r_max=float(r_max),
        n_max=int(n_max), force_body=_FORCE_BODIES[force_kernel])


# ---------------------------------------------------------------------------
# Toolchain + checkout resolution
# ---------------------------------------------------------------------------

def find_nvcc() -> str | None:
    """Return the path to ``nvcc`` if present, else ``None``."""
    return shutil.which("nvcc")


def cache_dir() -> Path:
    root = os.environ.get("PBG_YALLA_CACHE")
    base = Path(root) if root else Path.home() / ".cache" / "pbg-yalla"
    return base


def resolve_yalla_home(*, allow_clone: bool = True) -> Path:
    """Locate a ya||a checkout, cloning it on first use if permitted.

    Resolution order: ``$YALLA_HOME`` → ``~/code/yalla`` → clone of
    :data:`YALLA_REPO_URL` into the cache dir. Raises
    :class:`YallaCudaUnavailable` if no checkout can be obtained.
    """
    env = os.environ.get("YALLA_HOME")
    candidates = []
    if env:
        candidates.append(Path(env))
    candidates.append(Path.home() / "code" / "yalla")
    cached = cache_dir() / "yalla"
    candidates.append(cached)

    for path in candidates:
        if (path / "include" / "solvers.cuh").is_file():
            return path

    if not allow_clone:
        raise YallaCudaUnavailable(
            "no ya||a checkout found. Set YALLA_HOME to a clone of "
            f"{YALLA_REPO_URL} (must contain include/solvers.cuh).")

    if shutil.which("git") is None:
        raise YallaCudaUnavailable(
            "ya||a is not present and git is unavailable to clone it. "
            f"Manually clone {YALLA_REPO_URL} and set YALLA_HOME.")

    cached.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "clone", "--depth", "1", YALLA_REPO_URL, str(cached)],
        check=True, capture_output=True, text=True)
    if not (cached / "include" / "solvers.cuh").is_file():
        raise YallaCudaUnavailable(
            f"cloned ya||a into {cached} but include/solvers.cuh is missing.")
    return cached


# ---------------------------------------------------------------------------
# Compile + run
# ---------------------------------------------------------------------------

def _binary_key(source: str, arch: str, nvcc: str) -> str:
    h = hashlib.sha1()
    h.update(source.encode())
    h.update(arch.encode())
    h.update(nvcc.encode())
    return h.hexdigest()[:16]


def compile_model(source: str, *, arch: str | None = None,
                  yalla_home: Path | None = None) -> Path:
    """Compile ``source`` against ya||a with nvcc; return the cached binary path.

    Recompiles only when the source/arch/toolchain change (content-addressed).
    Raises :class:`YallaCudaUnavailable` if nvcc is missing.
    """
    nvcc = find_nvcc()
    if nvcc is None:
        raise YallaCudaUnavailable(
            "nvcc not found — the real ya||a bridge needs the CUDA toolkit and "
            "an NVIDIA GPU. Run on a CUDA host (Colab, a rental GPU box, or an "
            "HPC node), or use YallaReproductionProcess for a CPU/NumPy run.")
    arch = arch or os.environ.get("YALLA_CUDA_ARCH", DEFAULT_CUDA_ARCH)
    yalla_home = yalla_home or resolve_yalla_home()
    include_dir = yalla_home / "include"

    key = _binary_key(source, arch, nvcc)
    build_dir = cache_dir() / "build" / key
    binary = build_dir / "model"
    if binary.is_file():
        return binary

    build_dir.mkdir(parents=True, exist_ok=True)
    cu_path = build_dir / "model.cu"
    cu_path.write_text(source)

    cmd = [
        nvcc, "-std=c++14", f"-arch={arch}",
        "-I", str(include_dir),
        str(cu_path), "-o", str(binary),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise YallaCudaUnavailable(
            f"nvcc failed compiling the ya||a model:\n{proc.stderr}")
    return binary


def write_state(path: Path, positions: np.ndarray, types: np.ndarray) -> None:
    """Write ``N`` then ``x y z type`` rows — the binary's input format."""
    X = np.asarray(positions, dtype=float).reshape(-1, 3)
    t = np.asarray(types).reshape(-1).astype(int)
    lines = [str(X.shape[0])]
    for (x, y, z), ti in zip(X, t):
        lines.append(f"{x:.9g}\t{y:.9g}\t{z:.9g}\t{int(ti)}")
    Path(path).write_text("\n".join(lines) + "\n")


def read_state(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Parse the binary's output file back into ``(positions[N,3], types[N])``."""
    tokens = Path(path).read_text().split()
    if not tokens:
        raise ValueError(f"empty state file: {path}")
    n = int(tokens[0])
    rest = tokens[1:]
    if len(rest) != 4 * n:
        raise ValueError(
            f"state file {path}: expected {4 * n} values for {n} cells, "
            f"got {len(rest)}")
    arr = np.array(rest, dtype=float).reshape(n, 4)
    return arr[:, :3].copy(), arr[:, 3].astype(np.int32)


def run_steps(binary: Path, positions: np.ndarray, types: np.ndarray, *,
              n_steps: int, dt: float, timeout: float = 120.0,
              workdir: Path | None = None) -> tuple[np.ndarray, np.ndarray]:
    """Advance the population ``n_steps`` of size ``dt`` via the compiled binary."""
    import tempfile

    workdir = workdir or Path(tempfile.mkdtemp(prefix="pbg-yalla-"))
    workdir.mkdir(parents=True, exist_ok=True)
    in_path = workdir / "state_in.tsv"
    out_path = workdir / "state_out.tsv"
    write_state(in_path, positions, types)

    cmd = [str(binary), str(in_path), str(out_path), str(int(n_steps)), repr(float(dt))]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        raise YallaCudaUnavailable(
            f"ya||a binary exited {proc.returncode}:\n{proc.stderr}")
    return read_state(out_path)
